Rails/config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :users
  # root "articles#index"
end

Rails/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags
end

Rails/app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

Rails/app/models/tag.rb
class Tag < ApplicationRecord
has_many :article_tags, dependent: :destroy
has_many :articles, through: :article_tags
end

Rails/app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_one_attached :image
end

Rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Rails/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
    @tags = Tag.limit(5)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
    @tags = Tag.all
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @tags = Tag.all
    create_tag()
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    create_tag()
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
      @user = User.find(@article.user_id)
      @tags = Tag.all
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :user_id,  tag_ids: [])
    end

    def create_tag()
      params[:tag_names].each do |name|
        Tag.create!(name:name) if(!Tag.exists?(name:name))
      end
    end
end

Rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :image)
    end
end

Rails/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/app/helpers/articles_helper.rb
module ArticlesHelper
end

Rails/app/helpers/users_helper.rb
module UsersHelper
end

Rails/app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= article.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= article.user_id %>
  </p>

</div>

Rails/app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Rails/app/views/articles/edit.html.erb
<div class="editor-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">
        <ul class="error-messages">
          <%# <li>That title is required</li> %>
        </ul>
        <%= form_with(model: @article, local: true) do |form| %>
          <fieldset>
              <div class="form-group">
                <%= form.text_field :title, class: "form-control form-control-lg", placeholder: "Article Title" %>
              </div>
              <div class="form-group">
                <%= form.text_area :content, class: "form-control", rows: 8, placeholder: "Write your article (in markdown)" %>
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Enter tags" autocomplete="on" list="tag-data-list" id="tag-input" name="test" />
                <datalist id="tag-data-list">
                  <% @tags.each do |tag| %>
                    <option value="<%= tag.id %>,<%= tag.name %>" class="tag-option"></option>
                  <% end %>
                </datalist>
                <div id="tag-list" class="tag-list">
                  <% @article.tags.each do |tag|%>
                    <span class="tag-default tag-pill tag-event"> 
                      <i class="ion-close"></i> 
                      <%= tag.name %>
                      <input name="article[tag_ids][]" value=<%= tag.id %> autocomplete="off" type="hidden" id="tag_ids">
                      <input name="tag_names[]" value=<%= tag.name %> autocomplete="off" type="hidden" id="tag_ids">
                    </span>
                  <% end %>
                </div>
              </div>
              <input name="article[user_id]" value="1" type="hidden">
              <%= form.button "Publish Article", class: "btn btn-lg pull-xs-right btn-primary", type: "submit" %>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% content_for :head do %>
  <%= javascript_import_module_tag "tag" %>
<% end %>

Rails/app/views/articles/index.html.erb
<div class="home-page">
  <div class="banner">
    <div class="container">
      <h1 class="logo-font">conduit</h1>
      <p>A place to share your knowledge.</p>
    </div>
  </div>

  <div class="container page">
    <div class="row">
      <div class="col-md-9">
        <div class="feed-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link" href="">Your Feed</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="">Global Feed</a>
            </li>
          </ul>
        </div>
        <% @articles.each do |article| %>
          <div class="article-preview">
            <div class="article-meta">
              <a href="/profile/eric-simons">
                <%= image_tag article.user.image, class:"comment-author-img"%>
              </a>
              <div class="info">
                <a href="/profile/eric-simons" class="author"><%= article.user.name %></a>
                <span class="date"><%= article.created_at.strftime('%B %d')%></span>
              </div>
              <button class="btn btn-outline-primary btn-sm pull-xs-right">
                <i class="ion-heart"></i> 29
              </button>
            </div>
            <%= link_to article_path(article.id), class: "preview-link" do %>
              <h1><%= article.title %></h1>
              <p><%= article.content %></p>
              <span>Read more...</span>
              <ul class="tag-list">
                <% article.tags.each do |tag| %>
                  <li class="tag-default tag-pill tag-outline"><%= tag.name %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
        <% end %>
        <%# <ul class="pagination">
          <li class="page-item active">
            <a class="page-link" href="">1</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="">2</a>
          </li>
        </ul> %>
      </div>

      <div class="col-md-3">
        <div class="sidebar">
          <p>Popular Tags</p>

          <div class="tag-list">
            <% @tags.each do |tag| %>
              <a href="" class="tag-pill tag-default"><%= tag.name %></a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

Rails/app/views/articles/new.html.erb
<% content_for :head do %>
  <%= javascript_import_module_tag "tag" %>
<% end %>
<div class="editor-page">
  <div class="container page">
    <div class="row">
      <div class="col-md-10 offset-md-1 col-xs-12">
        <ul class="error-messages">
          <%# <li>That title is required</li> %>
        </ul>
        <%= form_with(model: @article, local: true) do |form| %>
          <fieldset>
              <div class="form-group">
                <%= form.text_field :title, class: "form-control form-control-lg", placeholder: "Article Title" %>
              </div>
              <div class="form-group">
                <%= form.text_area :content, class: "form-control", rows: 8, placeholder: "Write your article (in markdown)" %>
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Enter tags" autocomplete="on" list="tag-data-list" id="tag-input"/>
                <datalist id="tag-data-list">
                  <% @tags.each do |tag| %>
                    <option value="<%= tag.id %>,<%= tag.name %>" class="tag-option"></option>
                  <% end %>
                </datalist>
                <div id="tag-list" class="tag-list">
                </div>
              </div>
              <input name="article[user_id]" value="1" type="hidden">
              <%= form.button "Publish Article", class: "btn btn-lg pull-xs-right btn-primary", type: "submit" %>
          </fieldset>
        <% end %>

      </div>
    </div>
  </div>
</div>

Rails/app/views/articles/show.html.erb
<div class="article-page">
  <div class="banner">
    <div class="container">
      <h1><%= @article.title %></h1>

      <div class="article-meta">
        <a href="/profile/eric-simons">
          <%= image_tag @user.image, class:"comment-author-img" if @user.image.attached?%>
        </a>
        <div class="info">
          <a href="/profile/eric-simons" class="author"><%= @user.name %></a>
          <span class="date"><%= @article.created_at.strftime('%B %d')%></span>
        </div>
        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-plus-round"></i>
          &nbsp; Follow <%= @user.name %> <span class="counter">(10)</span>
        </button>
        &nbsp;&nbsp;
        <button class="btn btn-sm btn-outline-primary">
          <i class="ion-heart"></i>
          &nbsp; Favorite Post <span class="counter">(29)</span>
        </button>
        <%= link_to edit_article_path(@article.id), class:"btn btn-sm btn-outline-secondary", method: :get do%>
          <i class="ion-edit"></i> Edit Article
        <% end %>
        <%= link_to article_path(@article.id), class:"btn btn-sm btn-outline-danger",method: :delete do%>
          <i class="ion-trash-a"></i> Delete Article
        <% end %>
      </div>
    </div>
  </div>

  <div class="container page">
    <div class="row article-content">
      <div class="col-md-12">
        <p>
          <%= @article.content %>
        </p>
        <ul class="tag-list">
          <% @article.tags.each do |tag| %>
            <li class="tag-default tag-pill tag-outline"><%= tag.name %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <hr />

    <div class="article-actions">
      <div class="article-meta">
        <a href="profile.html">
          <%= image_tag @user.image, class:"comment-author-img"%>
        </a>
        <div class="info">
          <a href="" class="author"><%= @user.name %></a>
          <span class="date"><%= @article.created_at.strftime('%B %d')%></span>
        </div>

        <button class="btn btn-sm btn-outline-secondary">
          <i class="ion-plus-round"></i>
          &nbsp; Follow Eric Simons
        </button>
        &nbsp;
        <button class="btn btn-sm btn-outline-primary">
          <i class="ion-heart"></i>
          &nbsp; Favorite Article <span class="counter">(29)</span>
        </button>
        <%= link_to edit_article_path(@article.id), class:"btn btn-sm btn-outline-secondary", method: :get do%>
          <i class="ion-edit"></i> Edit Article
        <% end %>
        <%= link_to article_path(@article.id), class:"btn btn-sm btn-outline-danger",method: :delete do%>
          <i class="ion-trash-a"></i> Delete Article
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-8 offset-md-2">
        <form class="card comment-form">
          <div class="card-block">
            <textarea class="form-control" placeholder="Write a comment..." rows="3"></textarea>
          </div>
          <div class="card-footer">
            <%= image_tag @user.image, class:"comment-author-img"%>
            <button class="btn btn-sm btn-primary">Post Comment</button>
          </div>
        </form>

        <div class="card">
          <div class="card-block">
            <p class="card-text">
              With supporting text below as a natural lead-in to additional content.
            </p>
          </div>
          <div class="card-footer">
            <a href="/profile/author" class="comment-author">
              <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            </a>
            &nbsp;
            <a href="/profile/jacob-schmidt" class="comment-author">Jacob Schmidt</a>
            <span class="date-posted">Dec 29th</span>
          </div>
        </div>

        <div class="card">
          <div class="card-block">
            <p class="card-text">
              With supporting text below as a natural lead-in to additional content.
            </p>
          </div>
          <div class="card-footer">
            <a href="/profile/author" class="comment-author">
              <img src="http://i.imgur.com/Qr71crq.jpg" class="comment-author-img" />
            </a>
            &nbsp;
            <a href="/profile/jacob-schmidt" class="comment-author">Jacob Schmidt</a>
            <span class="date-posted">Dec 29th</span>
            <span class="mod-options">
              <i class="ion-trash-a"></i>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

Rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Conduit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="//demo.productionready.io/main.css" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield :head %>
  </head>
  <nav class="navbar navbar-light">
    <div class="container">
      <%= link_to articles_path, class: "navbar-brand", method: :get do %>
        conduit
      <%end%>
      <ul class="nav navbar-nav pull-xs-right">
        <li class="nav-item">
          <!-- Add "active" class when you're on that page" -->
          <a class="nav-link active" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/login">Sign in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/register">Sign up</a>
        </li>
      </ul>
    </div>
  </nav>
  <body>
    <%= yield %>
  </body>
<footer>
  <div class="container">
    <a href="/" class="logo-font">conduit</a>
    <span class="attribution">
      An interactive learning project from <a href="https://thinkster.io">Thinkster</a>. Code &amp;
      design licensed under MIT.
    </span>
  </div>
</footer>
</html>

Rails/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

Rails/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= image_tag user.image, size: "150x100" if user.image.attached?%>
  </p>


</div>

Rails/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

Rails/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

Rails/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

Rails/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>